# Generated by Django 5.1.3 on 2024-12-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_order_products_remove_cart_products_and_more'),
        ('product', '0004_alter_product_likes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
