# Generated by Django 5.1.3 on 2024-11-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_joined',
            new_name='joined_at',
        ),
    ]
