# Generated by Django 5.1.3 on 2024-11-15 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_addresses_user_default_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={'ordering': ('-created_at',), 'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterField(
            model_name='user',
            name='default_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for', to='account.addresses'),
        ),
    ]
