# Generated by Django 5.1.3 on 2024-11-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='sliders/img/')),
                ('is_visable', models.BooleanField(default=True)),
                ('link', models.CharField(blank=True, max_length=2048, null=True)),
                ('index', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'slider',
                'verbose_name_plural': 'sliders',
                'ordering': ('-index',),
            },
        ),
    ]
