# Generated by Django 5.1.3 on 2024-11-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='index',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
    ]
